steps:
- id: "Install node modules"
  name: gcr.io/cloud-builders/npm
  # dir: functions
  args: ['install']

- id: "Lint"
  name: gcr.io/cloud-builders/npm
  dir: functions
  args: ['run', 'lint']

# - id: "Test"
#   name: gcr.io/cloud-builders/npm
#   dir: functions
#   args: ['test']

- id: "Deploy"
  name: gcr.io/cloud-builders/gcloud
  # dir: functions
  args: ['functions', 'deploy', 'pokeapi', '--entry-point', 'pokeapi' '--region=europe-west1', '--trigger-http']
  args: ['functions', 'deploy', 'hello', '--entry-point', 'helloworld' '--region=europe-west1', '--trigger-http']

# - id: "Deploy"
#   name: gcr.io/cloud-builders/gcloud
#   # dir: functions
#   args: ['functions', 'deploy', 'hello', '--entry-point', 'helloworld' '--region=europe-west1', '--trigger-http']